notes: Update

diff --git a/notes/+WIP-NOTES-QUBES-KVM.yaml b/notes/+WIP-NOTES-QUBES-KVM.yaml
--- a/notes/+WIP-NOTES-QUBES-KVM.yaml
+++ b/notes/+WIP-NOTES-QUBES-KVM.yaml
@@ -41,6 +41,162 @@ WIP:
   kvmchand fixed:
     - BUG - libvirt.c setting chardev
 
+  vm:
+    # --------------------------------------------------------------------------
+    BOOT:
+      UEFI: Missing efi configuration
+      grub: Missing grub configuration
+      fstab: Incorrect fstab entry
+      kernel: Built qubes kernel does not get installed
+      QUBES PACKAGES: Out of date (rebuild templates)
+      DISABLE SERVICES NOT IMPLEMENTED: |
+        sudo systemctl disable qubes-iptables.service
+        sudo systemctl disable qubes-network.service
+        sudo systemctl disable qubes-firewall.service
+        sudo systemctl disable qubes-updates-proxy.service
+        sudo systemctl disable qubes-updates-proxy-forwarder.socket
+
+    # --------------------------------------------------------------------------
+    ## NO NETWORK
+    ## HACK:  Comment out or remove 30_qubes.conf
+    ## TODO:
+    ##  - Where does 'network-manager' service get set
+    /usr/lib/systemd/system/NetworkManager.service.d/30_qubes.conf: |
+      [Unit]
+      ConditionPathExists=/var/run/qubes-service/network-manager
+      # For /rw
+      After=qubes-mount-dirs.service
+      # For /var/run/qubes-service
+      After=qubes-sysinit.service
+      [Service]
+      ExecStartPre=/usr/lib/qubes/network-manager-prepare-conf-dir
+
+    # --------------------------------------------------------------------------
+    /etc/dnf/dnf.conf: | TEMP HACK in qubes-sysinit - FIX AFTER TEST
+      NOTE: | TEMP HACK WORKS.  Implement fix as described below
+      ### QUBES BEGIN ###
+      # This part of configuration, until QUBES END, is automatically generated by
+      # /usr/lib/qubes/update-proxy-configs. All changes here will be overriden.
+      # If you want to override any option set here, set it again to desired value,
+      # below this section
+      proxy=http://127.0.0.1:8082/
+      ### QUBES END ###
+
+      /usr/lib/qubes/init/qubes-sysinit.sh:
+        sets: /var/run/qubes-service/updates-proxy-setup
+        issue:  When set proxy gets added to /etc/dnf/dnf.conf
+        solution: |
+          /usr/lib/qubes/init/qubes-sysinit.sh could call qubeskvm-sysinit.sh
+          to add code to disable setting ***MIGHT BE TEMP CODE until network
+          implemented***
+
+    GUI: | HACK: instlled with --allowerasing
+         # May need to take that into account when adding via template
+      - dnf groupinstall -y "Xfce Desktop"
+      # Error:
+      #  Problem 1: conflicting requests
+      #   - package qubes-core-agent-4.1.14-1.fc32.x86_64 conflicts with firewalld provided by firewalld-0.8.3-1.fc32.noarch
+      #   - package qubes-core-agent-4.1.14-1.fc32.x86_64 conflicts with firewalld provided by firewalld-0.8.2-2.fc32.noarch
+      #   - problem with installed package qubes-core-agent-4.1.14-1.fc32.x86_64
+      # Problem 2: conflicting requests
+      #   - package firewall-config-0.8.3-1.fc32.noarch requires firewalld = 0.8.3-1.fc32, but none of the providers can be installed
+      #   - package firewall-config-0.8.2-2.fc32.noarch requires firewalld = 0.8.2-2.fc32, but none of the providers can be installed
+      #   - package qubes-core-agent-4.1.14-1.fc32.x86_64 conflicts with firewalld provided by firewalld-0.8.3-1.fc32.noarch
+      #   - package qubes-core-agent-4.1.14-1.fc32.x86_64 conflicts with firewalld provided by firewalld-0.8.2-2.fc32.noarch
+      #   - package qubes-core-agent-dom0-updates-4.1.14-1.fc32.x86_64 requires qubes-core-agent = 4.1.14, but none of the providers can be installed
+      #   - problem with installed package qubes-core-agent-dom0-updates-4.1.14-1.fc32.x86_64
+      # Problem 3: problem with installed package curl-minimal-7.69.1-5.fc32.x86_64
+      #   - package curl-minimal-7.69.1-5.fc32.x86_64 conflicts with curl provided by curl-7.69.1-1.fc32.x86_64
+      #   - package curl-minimal-7.69.1-1.fc32.x86_64 conflicts with curl provided by curl-7.69.1-1.fc32.x86_64
+      #   - conflicting requests
+      #   - package curl-minimal-7.69.1-5.fc32.x86_64 conflicts with curl provided by curl-7.69.1-5.fc32.x86_64
+      #   - package curl-minimal-7.69.1-1.fc32.x86_64 conflicts with curl provided by curl-7.69.1-5.fc32.x86_64
+      # (try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)
+      dnf groupinstall -y --allowerasing "Xfce Desktop":
+        - dnf install passwd
+        - passwd user  # set password
+        - reboot
+        - sudo virt-viewer fedora-32
+        - login as user
+        - startxfce4 || unset DISPLAY && startxfce4 &
+        NOTES:
+          installed with --allowerasing:
+            - Once GUI was installed, console required logging in
+            - qubes-db and qrexec services did not start on boot
+          dnf groupinstall -y --skip-broken "Xfce Desktop":
+            - /var/run/qubes/qrexec-server.user.sock= created
+            - qvm-run works
+          # XXX:  Try qubes xfce4 package?
+
+        ISSUES: | Removed many packages due to removing curl-minimal
+          Removing dependent packages:
+          curl-minimal                        x86_64  7.69.1-5.fc32                       @updates                233 k
+          qubes-core-agent                    x86_64  4.1.14-1.fc32                       @template-builder-repo  304 k
+          qubes-core-agent-dom0-updates       x86_64  4.1.14-1.fc32                       @template-builder-repo  7.2 k
+            qubes-core-agent-nautilus           x86_64  4.1.14-1.fc32                       @template-builder-repo  6.6 k
+            qubes-core-agent-network-manager    x86_64  4.1.14-1.fc32                       @template-builder-repo  3.2 k
+            qubes-core-agent-networking         x86_64  4.1.14-1.fc32                       @template-builder-repo   25 k
+            qubes-core-agent-systemd            x86_64  4.1.14-1.fc32                       @template-builder-repo  9.3 k
+            qubes-gui-agent                     x86_64  4.1.10-1.fc32                       @template-builder-repo  173 k
+            qubes-vm-dependencies               noarch  4.1.9-1.fc32                        @template-builder-repo    0
+            qubes-vm-recommended                noarch  4.1.9-1.fc32                        @template-builder-repo    0
+      dnf groupinstall -y --skip-broken "Xfce Desktop":
+        Skipped:
+        curl-7.69.1-5.fc32.x86_64               curl-minimal-7.69.1-1.fc32.x86_64
+        firewall-config-0.8.3-1.fc32.noarch     firewalld-0.8.3-1.fc32.noarch
+
+
+    # --------------------------------------------------------------------------
+    qrexec-fork-server:
+      ##TEMP-FIX: | # XXX: TEMP until GUI implemented
+      ##  qubes-qrexec-agent.service.d/30_qubes-kvm.conf:
+      ##  ExecStartPost=/usr/bin/qrexec-fork-server
+      #### NO WORK:  Need user logged in
+      exec: /etc/xdg/autostart/qubes-qrexec-fork-server.desktop
+      issue: Only starts if gui started
+      issue: |
+        /etc/qubes-rpc/qubes.WaitForSession is called until executed
+        for /var/run/qubes/qrexec-server.$USERNAME.sock to be created
+      issue: |
+        Apps on host like 'qvm-run --pass-io 'date' won't run (hangs) unless
+        fork-server started
+      solution: Starting GUI may fix.  Wonder about if only console started?
+
+    # --------------------------------------------------------------------------
+    /etc/xdg:
+      - May be more required apps not starting.
+
+    # --------------------------------------------------------------------------
+    VOLATILE.IMG:
+      # Based on ROOT_DEV size?  Maybe not required and will be auto created?
+      linux-utils/dracut/full-dmroot/qubes_cow_setup.sh: |
+        if [ `cat /sys/class/block/$ROOT_DEV/ro` = 1 ] ; then
+        log_begin "Qubes: Doing COW setup for AppVM..."
+        #
+        while ! [ -e /dev/xvdc ]; do sleep 0.1; done
+        VOLATILE_SIZE=$(cat /sys/class/block/xvdc/size) # sectors
+        ROOT_SIZE=$(cat /sys/class/block/$ROOT_DEV/size) # sectors
+        if [ $VOLATILE_SIZE -lt $SWAP_SIZE ]; then
+            die "volatile.img smaller than 1GB, cannot continue"
+        fi
+        sfdisk -q --unit S /dev/xvdc >/dev/null <<EOF
+
+    # --------------------------------------------------------------------------
+    SYSTEMD DROP-INS:
+      Conditional drop-ins would prevent qubes from running in xen if the kvm
+      hypervisor was not present.  Seems like the drop-ins are read one at a
+      time and just overwrites the existing unit file.
+
+      OPTIONS:
+        1:  Have kvm package add the dropins.  This does not allow for the VM
+            to be swapable with Qubes-XEN.
+        2:  systemd-generators to create drop-ins on the fly (if possible).
+            Could have the hypervisor init script add/remove dropins based on
+            the hypervisor type but would most likely require a reboot.
+
+    # --------------------------------------------------------------------------
+    # --------------------------------------------------------------------------
+
 ################################################################################
 TESTS:
   # journalctl -xn -u kvmchand | less
@@ -419,6 +575,32 @@ NOTES:
       #  start: /usr/bin/qvm-start --skip-if-running %i
 
   vm:
+    QUBES SCRIPTS RUN AT BOOT IN RUN ORDER:
+      qubes-kvm: kvmchand.service
+      #udev-block-add-change (X3):
+      #udev-usb-add-change:
+      #udev-block-add-change:
+      #udev-usb-add-change (X4):
+      qubes-sysinit.sh: qubes-sysinit.service
+      #udev-block-add-change (X6):
+      qubes-random-seed.sh: systemd-random-seed.service.d/30_qubes.conf
+      mount-dirs.sh: qubes-mount-dirs.service
+      resize-rootfs-if-needed.sh: qubes-rootfs-resize.service
+      setup-rwdev.sh: qubes-mount-dirs.service # FROM mount-dirs.sh
+      #udev-block-add-change (X2):
+      setup-rw.sh: qubes-mount-dirs.service # FROM mount-dirs.sh
+      #udev-block-add-change (X2):
+      resize-rootfs: qubes-rootfs-resize.service
+      bind-dirs.sh: qubes-mount-dirs.service # FROM mount-dirs.sh
+      #udev-block-add-change (X15):
+      qubes-early-vm-config.sh: qubes-early-vm-config.service
+      #udev-block-add-change (X2):
+      misc-post.sh: qubes-misc-post.service
+      update-proxy-configs: qubes-misc-post.service # FROM misc-post.sh
+      setup-ip: qubes-misc-post.service # FROM misc-post.sh + FROM network-manager-prepare-conf-dir
+      control-printer-icon.sh: cups.service.d/30_qubes.conf
+      #qubes-setup-dnat-to-ns (X3):
+
     systemd-services:
       # --- SYSINIT TARGETS ----------------------------------------------------
       # ENABlED
